.TH MRSS "1" "May 2022"
.SH NAME
mrss \- transform web feeds to Maildir mails
.
.SH SYNOPSIS
.
.B mrss
.RI "[ --" COMMAND "=" ARG " | --" COMMAND " " ARG " ]..."
.
.SH DESCRIPTION
.B mrss
creates Maildir mail messages from RSS or Atom feeds.
.
.SH COMMANDS
.P
Commands are executed sequentally.
.
.TP
.BI cd\  SHELL-STRING
Change current working directory.
.
.IP
Mails are created in
.BR new
directory.
.
.IP
Substitutes
.B ~
and recognizes environment variables.
.
.TP
.BI config\  STRING
Read file lines and execute whitespace separated
.IR COMMAND - ARG
pairs.
.IP
Empty lines and lines starting with hash mark
.RB ( # )
are ignored.
.
.TP
.BI expire\  INTEGER
Specify minimum time of expiration in seconds. Non-expired feeds are considered
up-to-date and no contact is made to the server. Number may be optionally
suffixed with
.BR d ay,\  h our,\  m inute\ or\  s econd
units.
.
.IP
If server sends Expires: header, the later time will be chosen.
.
.TP
.BI from\  STRING
Set From: header for next feed.
.
.TP
.BI include\  SHELL-STRING
Synonym of
.BR config ,
except it takes a SHELL-STRING.
.
.TP
.BI proxy\  STRING
Use proxy. Default: (empty) (no proxy).
.IP
Example: socks5://127.0.0.1:9050.
.
.TP
.BI reply_to\  CHOICE
Create a root mail for the channel in
.B cur
directory and reply to it. Default: yes.
.
.TP
.BI url\  STRING
Open feed specified by the URL.
.IP
URLs in the form of
.BI system: COMMAND
execute shell
.I COMMAND
and expect XML content on the standard output. Empty output is treated as HTTP
304 (Not Modified).
.
.TP
.BI urls\  STRING
Read file lines and execute
.B url
command for each line.
.IP
Empty lines and lines starting with hash mark
.RB ( # )
are ignored.
.
.TP
.BI user_agent\  STRING
Set User-Agent: header to be used in HTTP requests. Default: (empty) (not sent).
.
.TP
.BI verbose\  CHOICE
Specify whether to show debug messages.
.
.SH "SEE ALSO"
.B mutt(1)
